[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "maze"
version = "0.1.0"
dependencies = [
    "pypng",
    "pytest>=8"
]

[tool.scikit.dependencies]
python = "^3.10"