[build-system]
requires = ["setuptools", "pybind11"]
build-backend = "setuptools.build_meta"

[project]
name = "pmazeprof"
authors = [{name = "Peter Freedman"}]
dynamic = ["version"]
dependencies = [
    "setuptools",
    "pybind11",
]





